config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portraits do
    resources :comments
    member do
      put "like", to: "portraits#upvote"
    end
  end

  root "portraits#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :portrait
  belongs_to :user
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :portraits
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_portrait, only: [:create, :destroy]
  before_action :authenticate_user!

  def create
    @comment = @portrait.comments.new(comments_params)
    @comment.user = current_user
    @comment.save

    redirect_to portrait_path(@portrait)
  end

  def destroy
    @comment = @portrait.comments.find(params[:id])
    @comment.destroy

    redirect_to portrait_path(@portrait)
  end

  private
  def comments_params
    params.require(:comment).permit(:content)
  end

  def find_portrait
    @portrait = Portrait.find(params[:portrait_id])
  end
end

app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  before_action :find_portrait, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @portraits = Portrait.all.order("created_at DESC")
  end

  def show
  end

  def new
    @portrait = current_user.portraits.build
  end

  def create
    @portrait = current_user.portraits.build(portrait_params)

    if @portrait.save
      redirect_to @portrait, notice: "Successfully created new Portrait"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @portrait.update(portrait_params)
      redirect_to @portrait, notice: "Portrait was Successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @portrait.destroy
    redirect_to root_path
  end

  def upvote
    @portrait.upvote_by current_user
    redirect_to :back
  end

  private
  def portrait_params
    params.require(:portrait).permit(:title, :description, :image)
  end

  def find_portrait
    @portrait = Portrait.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/views/comments/_comment.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-10
        %comment_user= comment.user.email
      .col-md-2
        - if user_signed_in?
          = link_to "Delete", [comment.portrait, comment], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
  .panel-body
    %p.comment_content= comment.content
  .panel-footer
    %p.comment_time
      = time_ago_in_words(comment.created_at)
      ago

app/views/comments/_form.html.haml
= simple_form_for [@portrait, @portrait.comments.build], html: { multpart: true } do |f|
  .form-group
    = f.input :content, input_html: { class: 'form_control' }

  = f.button :submit, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title PortraitBook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        .navbar-brand= link_to "Portrait Book", root_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "New Portrait", new_portrait_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        -else
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container-fluid{:style => "padding-top: 70px"}
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/portraits/_form.html.haml
= simple_form_for @portrait, html: { multpart: true } do |f|
  - if @portrait.errors.any?
    #errors
      %h2
        = pluralize(@portrait.errors.count, "errors")
        prevent this Portrait from saving
        %ul
          - @portrait.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: "btn btn-primary"

app/views/portraits/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Portrait
      .panel-body
        %strong.center Current Image
        %br/
        = image_tag @portrait.image.url(:medium)
        %br/
        = render 'form'

app/views/portraits/index.html.haml
#portraits.transitions-enabled
  - @portraits.each do |portrait|
    .box.panel.panel-default
      .panel-heading
        .img-thumbnail
          = link_to (image_tag portrait.image.url(:medium)), portrait
      .panel-body
        %h2= link_to portrait.title, portrait
      .panel-footer
        %p.user
          Submitted by
          = portrait.user.email

app/views/portraits/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Portrait
      .panel-body
        = render 'form'

app/views/portraits/show.html.haml
#portrait_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.portrait_image
        .img-thumbnail
          = image_tag @portrait.image.url
      .panel-body
        %h1= @portrait.title
        %p.description= @portrait.description
      .panel-footer
        .row
          .col-md-8
            %p.user
              Submitted
              = time_ago_in_words(@portrait.created_at)
              ago by
              = @portrait.user.email
          .col-md-4
            .btn-group.pull-right
            = link_to like_portrait_path(@portrait), method: :put, class: "btn btn-default" do
              %span.glyphicon.glyphicon-heart
                = @portrait.get_upvotes.size
            - if user_signed_in?
              = link_to "Edit", edit_portrait_path, class: "btn btn-default"
              = link_to "Delete", portrait_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
#comment.row
  .col-md-8.col-md-offset-2
    %h2
      = @portrait.comments.count
      Comments
    .panel.panel-default
      .panel-body
        = render @portrait.comments
    %h3 Add a comment:
    .panel.panel-default
      .panel-body
        = render "comments/form"